version: '3' # versão do yaml

services:
  user-crud-database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
    container_name: user-crud-database
    ports:
      - '3002:3306'
    volumes:
      - ./.docker/db:/var/lib/mysql
    restart: unless-stopped
